### ISSUE TITLE
Catkin make issue

### ISSUE THREAD

**Issue by zensim38** [homer-robotics/homer_robot_face#6]
Hi,
I did a catkin_make and got the following error messages:
the following variables are used in this project, but they are set to notfound. please set them or make sure they are set and tested correctly in the cmake files: festival_libraries linked by target "robotface" in directory /home/ubuntu/catkin_hs/src/homer_robot_face -- configuring incomplete, errors occurred!

I have since install the festival-dev and package and still cannot complie it. Could you kindly advise pls

**Comment by vseib** [comment]
Hello zensim38,

assuming that festival is installed correctly, a common error cause is that cmake is not generating new data, but is instead using some cached files.
Try running "catkin clean" in your workspace (or delete the devel and build folders). Surely, there is a way to clean only the data for a specific package (maybe "catkin clean --pkg robot_face" - or similar).
After cleaning up, try to make it again.

If it does not help, look inside the variable that is causing the error. Try adding 
`message("content of festival_libraries: " $festival_libraries)`
and see if the variable contains something. If it does not, catkin is not able to find your installation of festival.

Good luck!

**Comment by zensim38** [comment]
Thanks Vseib. I reinstall festival and it is working. By the way, May I know how I can change the images of the robot so it can display them instead of the given images and emotions?

**Comment by zensim38** [comment]
Wondering also how I can expand the robot face to full window size if I am using the original robot? I try changing the config parameters but it doesnt work.

**Comment by vseib** [comment]
Hi again,

for your first question, maybe Issue #4  can be of help. Basically, there are special topics to publish an image on that can be displayed.
For the second question: My answer would have been indeed to look into the config. Since this is not working, please double check which config you used. By looking into the config folder, I see 4 configs, but I am not sure anymore which is loaded by default. Maybe you used the wrong one (but this is just a guess)?

Maybe the Article "A ros-based system for an autonomous service robot" can be of help to you. You can look it up on Google Scholar or a similar page. In there is a section dedicated to the robot face, which might provide additional information to you.

Best

**Comment by zensim38** [comment]
Thank you so much Vseib :)
